{
	"name": "ci",
	"on": {
		"push": {
			"branches": [
				"main"
			]
		}
	},
	"jobs": {
		"lint": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "find . -"
				},
				{
					"run": "npx eslint --ignore-pattern \"public/**/*\" --quiet \"**/*.ts\""
				}
			]
		}
	}
}
