{
	"name": "ci",
	"on": {
		"push": {
			"branches": [
				"main"
			]
		}
	},
	"jobs": {
		"lint": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm install eslint@7.32.0 typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser"
				},
				{
					"run": "npx eslint --ignore-pattern \"public/**/*\" --quiet \"**/*.ts\""
				}
			]
		},
		"build": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run build"
				}
			]
		},
		"test": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run test"
				}
			]
		},
		"publish": {
			"runs-on": "ubuntu-latest",
			"needs": ["lint", "build", "test"],
			"env": {
				"NODE_AUTH_TOKEN": "${{ secrets.NPM_TOKEN }}"
			},
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm build"
				},
				{
					"run": "npm publish"
				}
			]
		}
	}
}
