{
	"name": "ci",
	"on": {
		"push": {
			"branches": [
				"main"
			]
		}
	},
	"jobs": {
		"lint": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
				{
					"run": "npm install eslint@7.32.0 typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser"
				},
				{
					"run": "npx eslint --ignore-pattern \"public/**/*\" --quiet \"**/*.ts\""
				}
			]
		}
	}
}
